name: Debug build APK

on:
  push:
    branches:
      - main
    paths-ignore:
      - ".gitignore"
      - "README.md"
      - "LICENSE"
      - ".idea/**"
      - ".github/**"
      - ".editorconfig"
  workflow_dispatch:

jobs:
  run:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: "oracle"
          java-version: "17"
          cache: "gradle"

      - name: Build debug APK
        run: |
          ./gradlew assembleDebug

      - name: Upload debug APK
        uses: actions/upload-artifact@v4
        with:
          name: debug-${{ github.sha }}
          path: ${{ github.workspace }}/app/build/outputs/apk/debug/app-debug.apk
